org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.1.33
forge_version_range=[47,)
loader_version_range=[47,)
parchment_version=2023.09.03

mod_id=whistles
mod_name=Train Whistles
mod_license=MIT
mod_version=0.1.0
mod_group_id=me.almana.whistles
mod_authors=
mod_description=Custom, pitch-bendable horns and whistles for Create trains.

create_version=6.0.8-291
create_version_range=[6.0,)
ponder_version=1.0.91
flywheel_version=1.0.6-beta-266
registrate_version=MC1.20-1.3.3
mixin_extras_version=0.4.1
